CREATE TABLE Questions(
   question_id    INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,question_text  VARCHAR(500) NOT NULL
  ,option_1       VARCHAR(255) NOT NULL
  ,option_2       VARCHAR(255) NOT NULL
  ,option_3       VARCHAR(255) NOT NULL
  ,option_4       VARCHAR(255) NOT NULL
  ,correct_answer VARCHAR(255) NOT NULL
);
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (1,'A library has an average of 510 visitors on Sundays and 240 on other days. The average number of visitors per day in a month of 30 days beginning with a Sunday is:','250','276','280','285','285');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (2,'The average monthly income of P and Q is Rs. 5050. The average monthly income of Q and R is Rs. 6250 and the average monthly income of P and R is Rs. 5200. The monthly income of P is:','3500','4000','4050','5000','4000');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (3,'The sum of two number is 25 and their difference is 13. Find their product.','104','114','315','325','114');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (4,'Speed of a boat in standing water is 9 kmph and the speed of the stream is 1.5 kmph. A man rows to a place at a distance of 105 km and comes back to the starting point. The total time taken by him is:','16 hours','18 hours','20 hours','24 hours','24 hours');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (5,'The angle between the minute hand and the hour hand of a clock when the time is 4:20, is:','0�','10�','5�','20�','10�');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (6,'Insert the missing number.  1, 4, 9, 16, 25, 36, 49, (....)','54','56','64','81','64');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (7,'The DBMS acts as an interface between what two components of an enterprise-class database system?','Database application and the database','Data and the database','The user and the database application','Database application and SQL','Database application and the database');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (8,'An on-line commercial site such as Amazon.com is an example of a(n) ________ .','single-user database application','multiuser database application','e-commerce database application','data mining database application','e-commerce database application');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (9,'An Enterprise Resource Planning application is an example of a(n) ________ .','single-user database application','multiuser database application','e-commerce database application','data mining database application','multiuser database application');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (10,'A DBMS that combines a DBMS and an application generator is ________ .','Microsoft''s SQL Server','Microsoft''s Access','IBM''s DB2','Oracle Corporation''s Oracle','Microsoft''s Access');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (11,'You have run an SQL statement that asked the DBMS to display data in a table named USER_TABLES. The results include columns of data labeled "TableName," "NumberOfColumns" and "PrimaryKey." You are looking at ________ .','user data.','metadata','A report','indexes','metadata');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (12,'What type of join is needed when you wish to return rows that do have matching values?','Equi-join','Natural join','Outer join','All of the above.','All of the above.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (13,'Which of the following statements is true concerning routines and triggers?','Both consist of procedural code.','Both have to be called to operate.','Both run automatically.','Both are stored in the database.','Both consist of procedural code.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (14,'The different classes of relations created by the technique for preventing modification anomalies are called:','normal forms.','referential integrity constraints.','functional dependencies.','None of the above is correct.','normal forms.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (15,'Which is a reserved word in the Java programming language?','method','native','subclasses','reference','native');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (16,'Which is a valid keyword in java?','interface','string','Float','unsigned','interface');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (17,'What is the name of the method used to start a thread execution?','init();','start();','run();','resume();','start();');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (18,'Which cannot directly cause a thread to stop executing?','Calling the�SetPriority()�method on a�Thread�object.','Calling the�wait()�method on an object.','Calling notify() method on an object.','Calling�read()�method on an�InputStream�object.','Calling notify() method on an object.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (19,'Which is true about an anonymous inner class?','It can extend exactly one class and implement exactly one interface.','It can extend exactly one class and can implement multiple interfaces.','It can extend exactly one class or implement exactly one interface.','It can implement multiple interfaces regardless of whether it also extends a class.','It can extend exactly one class or implement exactly one interface.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (20,'Which statement is true about a static nested class?','You must have a reference to an instance of the enclosing class in order to instantiate it.','It does not have access to nonstatic members of the enclosing class.','It''s variables and methods must be�static.','It must extend the enclosing class.','It does not have access to nonstatic members of the enclosing class.');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (21,'To keeps one''s temper','To become hungry','To be in good mood','To preserve ones energy','To be aloof from','To be in good mood');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (22,'Fate smiles ...... those who untiringly grapple with stark realities of life.','with','over','on','round','on');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (23,'I saw a ...... of cows in the field.','group','herd','swarm','flock','herd');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (24,'GRAIN:SALT','shard:pottery','shred:wood','blades:grass','chip:glass','chip:glass');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (25,'Look at this series: 2, 1, (1/2), (1/4), ... What number should come next?','(1/3)','(1/8)','(2/8)','(1/16)','(1/8)');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (26,'Look at this series: 53, 53, 40, 40, 27, 27, ... What number should come next?','12','14','27','53','14');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (27,'SCD, TEF, UGH, ____, WKL','CMN','UJI','VIJ','IJT','VIJ');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (28,'QAR, RAS, SAT, TAU, _____','UAV','UAT','TAS','TAT','UAV');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (29,'In how many different ways can the letters of the word ''LEADING'' be arranged in such a way that the vowels always come together?','360','480','720','5040','720');
INSERT INTO Questions(question_id,question_text,option_1,option_2,option_3,option_4,correct_answer) VALUES (30,'A tank is filled by three pipes with uniform flow. The first two pipes operating simultaneously fill the tank in the same time during which the tank is filled by the third pipe alone. The second pipe fills the tank 5 hours faster than the first pipe and 4 hours slower than the third pipe. The time required by the first pipe is:','6 hours','10 hours','15 hours','30 hours','15 hours');
